### ISSUE TITLE
On page-load: Default song plays regardless of content in queue

### ISSUE THREAD

**Issue by NateFuller** [FLMS-HackUmass/djq#9]
#### Steps to reproduce
- navigate to dj page
- there is a song in the queue
- default song will play anyways
#### Expected behavior

When the dj navigates to his/her page, the system should play the song at the head of the queue and dequeue that song instead of always play the default song. 
#### Workarounds
- Press the "Play Next Song" button to force-play the next song in the queue.
- The default song ends, triggering playback of the next song in the queue.

**Comment by stanleyrya** [comment]
You can also get the top video to play by pressing "Play Next Song".

**Comment by NateFuller** [comment]
Ah right forgot about that. Just edited the issue to account for that workaround.

**Comment by stanleyrya** [comment]
Ok. Not a work-around, but I know what you mean.

**Comment by stanleyrya** [comment]
Default song no longer plays. To start streaming queue, user must press "Play Next Song".
